### ISSUE TITLE
question: ¿how to compile the mod maker?

### ISSUE THREAD

**Issue by maxi230151** [EnigmaEngine/EnigmaModMaker#8]
¿how to compile the mod maker when compiled I only get lime.ndll?

**Comment by MasterEric** [comment]
1. The app is NOWHERE near being anywhere near being anywhere near done. Like seriously I just took some UI elements and put them next to each other to form a nice layout the app doesn't do anything useful yet.
2. I put compilation instructions in the readme here: https://github.com/EnigmaEngine/EnigmaModMaker#compiling

**Comment by prokube** [comment]
better put that in the readme then huh
